//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_AggregationStatistic
    {
        public CV_AggregationStatistic()
        {
            this.DataloggerFileColumns = new HashSet<DataloggerFileColumn>();
            this.MeasurementResults = new HashSet<MeasurementResult>();
            this.PointCoverageResults = new HashSet<PointCoverageResult>();
            this.ProfileResults = new HashSet<ProfileResult>();
            this.SectionResults = new HashSet<SectionResult>();
            this.SectionResultValues = new HashSet<SectionResultValue>();
            this.SpectraResults = new HashSet<SpectraResult>();
            this.TimeSeriesResults = new HashSet<TimeSeriesResult>();
            this.TrajectoryResults = new HashSet<TrajectoryResult>();
            this.TransectResults = new HashSet<TransectResult>();
            this.TransectResultValues = new HashSet<TransectResultValue>();
        }
    
        public string Term { get; set; }
        public string Name { get; set; }
        public string Definition { get; set; }
        public string Category { get; set; }
        public string SourceVocabularyURI { get; set; }
    
        public virtual ICollection<DataloggerFileColumn> DataloggerFileColumns { get; set; }
        public virtual ICollection<MeasurementResult> MeasurementResults { get; set; }
        public virtual ICollection<PointCoverageResult> PointCoverageResults { get; set; }
        public virtual ICollection<ProfileResult> ProfileResults { get; set; }
        public virtual ICollection<SectionResult> SectionResults { get; set; }
        public virtual ICollection<SectionResultValue> SectionResultValues { get; set; }
        public virtual ICollection<SpectraResult> SpectraResults { get; set; }
        public virtual ICollection<TimeSeriesResult> TimeSeriesResults { get; set; }
        public virtual ICollection<TrajectoryResult> TrajectoryResults { get; set; }
        public virtual ICollection<TransectResult> TransectResults { get; set; }
        public virtual ICollection<TransectResultValue> TransectResultValues { get; set; }
    }
}
